// Generates src/theme.css (a Tailwind v4 theme — our "preset") from design/tokens.json.
// Run after changing tokens: npm run tokens
import { readFileSync, writeFileSync } from "node:fs";

const tokensUrl = new URL("../../../design/tokens.json", import.meta.url);
const outUrl = new URL("../src/theme.css", import.meta.url);
const tokens = JSON.parse(readFileSync(tokensUrl, "utf8"));

// "brand/primary-50" -> "brand-primary-50", "Heading/H1 24" -> "heading-h1-24"
const slug = (name) => name.toLowerCase().replace(/[\s/]+/g, "-");

const lines = [];
for (const [name, t] of Object.entries(tokens.color)) lines.push(`  --color-${slug(name)}: ${t.$value};`);
// Spacing tokens (4, 8, 12 … 48 px) are all multiples of Tailwind's default 4px step, so p-1 = 4px,
// p-4 = 16px, p-12 = 48px already match; no variables needed.
for (const [name, t] of Object.entries(tokens.radius)) lines.push(`  --radius-${slug(name)}: ${t.$value};`);
for (const [name, t] of Object.entries(tokens.shadow)) {
  const layers = t.$value.map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`).join(", ");
  lines.push(`  --shadow-${slug(name)}: ${layers};`);
}
for (const [name, t] of Object.entries(tokens.typography)) {
  const v = t.$value;
  const key = slug(name);
  lines.push(`  --text-${key}: ${v.fontSize};`);
  lines.push(`  --text-${key}--line-height: ${parseFloat(v.lineHeight) / 100};`);
  lines.push(`  --text-${key}--font-weight: ${v.fontWeight};`);
}

const css = `/* GENERATED by packages/ui/scripts/build-theme.mjs from design/tokens.json — do not edit by hand. */
/* Usage: bg-brand-primary, text-status-danger-700, text-number-hero-44, rounded-lg, shadow-card */
@theme {
  --font-sans: var(--font-cairo), "Cairo", sans-serif;
${lines.join("\n")}
}
`;
writeFileSync(outUrl, css);
console.log(`wrote ${outUrl.pathname} (${lines.length} variables)`);
