-- =====================================================================
-- FuelOS — core schema
-- Multi-tenant: organization -> stations. Every station-owned row carries station_id.
-- Money: numeric(16,2). Liters: numeric(14,3). Meter readings: numeric(14,1).
-- Client-generated UUIDs are allowed on offline-created rows (shifts, sales).
-- =====================================================================

-- ---------- enums ----------
create type member_role        as enum ('owner', 'accountant', 'shift_manager', 'attendant');
create type platform_role      as enum ('platform_admin', 'support');
create type member_status      as enum ('active', 'invited', 'suspended');
create type station_status     as enum ('setup', 'active', 'suspended');
create type shift_status       as enum ('open', 'submitted', 'approved', 'rejected', 'reopened');
create type payment_method     as enum ('cash', 'card', 'credit', 'voucher');
create type sale_status        as enum ('recorded', 'pending_approval', 'voided');
create type invoice_status     as enum ('pending', 'confirmed', 'corrected', 'cancelled');
create type movement_type      as enum ('receipt', 'sale', 'adjustment', 'waste', 'return', 'transfer_in', 'transfer_out');
create type availability_status as enum ('available', 'limited', 'unavailable');
create type data_source        as enum ('computed', 'manual');
create type account_type       as enum ('asset', 'liability', 'equity', 'revenue', 'expense');
create type entry_status       as enum ('draft', 'posted');
create type period_status      as enum ('open', 'closed');
create type approval_type      as enum ('shift_close', 'credit_over_limit', 'stock_adjustment', 'shift_reopen');
create type approval_status    as enum ('pending', 'approved', 'rejected');
create type company_status     as enum ('active', 'frozen', 'suspended');
create type complaint_kind     as enum ('complaint', 'price_report');
create type complaint_status   as enum ('open', 'awaiting_station', 'resolved', 'escalated');
create type subscription_status as enum ('trial', 'active', 'past_due', 'cancelled', 'legacy');
create type ticket_priority    as enum ('low', 'medium', 'high');
create type ticket_status      as enum ('open', 'in_progress', 'resolved');
create type expense_category   as enum ('salaries', 'utilities', 'maintenance', 'transport', 'other');
create type cash_source        as enum ('cash', 'bank');

-- ---------- tenancy & people ----------
create table organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

create table stations (
  id                   uuid primary key default gen_random_uuid(),
  organization_id      uuid not null references organizations(id),
  name                 text not null,
  address              text,
  city                 text,
  timezone             text not null default 'UTC',
  currency_code        char(3) not null,                         -- e.g. 'SYP' (placeholder until confirmed)
  money_decimals       smallint not null default 2 check (money_decimals between 0 and 3),
  status               station_status not null default 'setup',
  -- tolerances (spec: differences above these need a reason + approval)
  cash_tolerance       numeric(16,2) not null default 1000 check (cash_tolerance >= 0),
  stock_tolerance_l    numeric(14,3) not null default 100 check (stock_tolerance_l >= 0),
  max_shift_hours      int not null default 12 check (max_shift_hours > 0),
  default_credit_limit numeric(16,2) not null default 250000 check (default_credit_limit >= 0),
  offline_max_ops      int not null default 50 check (offline_max_ops > 0),
  created_at           timestamptz not null default now()
);
create index on stations (organization_id);

create table platform_staff (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  role       platform_role not null,
  created_at timestamptz not null default now()
);

create table station_members (
  station_id   uuid not null references stations(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  role         member_role not null,
  status       member_status not null default 'invited',
  display_name text not null,
  pin_hash     text,                                -- attendants log in with a PIN on a registered device
  created_at   timestamptz not null default now(),
  primary key (station_id, user_id)
);
create index on station_members (user_id);

create table customers (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  phone       text unique,
  created_at  timestamptz not null default now()
);

create table devices (
  id              text primary key,                 -- device identifier generated by the app
  station_id      uuid not null references stations(id) on delete cascade,
  label           text,
  registered_by   uuid references auth.users(id),
  last_sync_at    timestamptz,
  pending_ops     int not null default 0,
  created_at      timestamptz not null default now()
);

-- ---------- catalog: products, tanks, pumps, prices ----------
create table products (
  id          uuid primary key default gen_random_uuid(),
  station_id  uuid not null references stations(id) on delete cascade,
  code        text not null,                        -- 'gasoline_90', 'gasoline_95', 'diesel'
  name        text not null,                        -- display name (Arabic)
  unit        text not null default 'L',
  is_active   boolean not null default true,
  unique (station_id, code),
  unique (station_id, id)
);

create table tanks (
  id             uuid primary key default gen_random_uuid(),
  station_id     uuid not null references stations(id) on delete cascade,
  product_id     uuid not null,
  name           text not null,
  capacity_l     numeric(14,3) not null check (capacity_l > 0),
  min_level_pct  numeric(5,2) not null default 20 check (min_level_pct between 0 and 100),
  is_active      boolean not null default true,
  foreign key (station_id, product_id) references products(station_id, id),
  unique (station_id, id)
);

create table pumps (
  id          uuid primary key default gen_random_uuid(),
  station_id  uuid not null references stations(id) on delete cascade,
  number      int not null check (number > 0),
  name        text,
  is_active   boolean not null default true,
  unique (station_id, number),
  unique (station_id, id)
);

create table nozzles (
  id            uuid primary key default gen_random_uuid(),
  station_id    uuid not null references stations(id) on delete cascade,
  pump_id       uuid not null,
  tank_id       uuid not null,                      -- a nozzle draws from exactly one tank
  label         text not null default '1',
  last_reading  numeric(14,1) not null default 0 check (last_reading >= 0),
  is_active     boolean not null default true,
  foreign key (station_id, pump_id) references pumps(station_id, id),
  foreign key (station_id, tank_id) references tanks(station_id, id),
  unique (station_id, id)
);

-- Price history. The current price is the latest effective_at <= now().
create table prices (
  id            uuid primary key default gen_random_uuid(),
  station_id    uuid not null references stations(id) on delete cascade,
  product_id    uuid not null,
  price         numeric(12,2) not null check (price > 0),
  effective_at  timestamptz not null default now(),
  published_by  uuid references auth.users(id),
  created_at    timestamptz not null default now(),
  foreign key (station_id, product_id) references products(station_id, id)
);
create index on prices (station_id, product_id, effective_at desc);

-- What customers see: availability with its source and time (no sensors => computed from book stock or manual).
create table product_availability (
  station_id  uuid not null references stations(id) on delete cascade,
  product_id  uuid not null,
  status      availability_status not null,
  source      data_source not null,
  updated_at  timestamptz not null default now(),
  updated_by  uuid references auth.users(id),
  primary key (station_id, product_id),
  foreign key (station_id, product_id) references products(station_id, id)
);

-- ---------- company (B2B credit) accounts ----------
create table company_accounts (
  id            uuid primary key default gen_random_uuid(),
  station_id    uuid not null references stations(id) on delete cascade,
  name          text not null,
  credit_limit  numeric(16,2) not null check (credit_limit >= 0),
  status        company_status not null default 'active',
  billing_day   smallint not null default 1 check (billing_day between 1 and 28),
  qr_token      text unique,                        -- printed on driver cards
  created_at    timestamptz not null default now(),
  unique (station_id, id)
);

create table company_drivers (
  id                  uuid primary key default gen_random_uuid(),
  company_account_id  uuid not null references company_accounts(id) on delete cascade,
  full_name           text not null,
  phone               text,
  is_authorized       boolean not null default true
);

create table vehicles (
  id                  uuid primary key default gen_random_uuid(),
  customer_id         uuid references customers(id) on delete cascade,
  company_account_id  uuid references company_accounts(id) on delete cascade,
  plate               text not null,
  label               text,                         -- 'كيا ريو 2019'
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  check ((customer_id is null) <> (company_account_id is null))
);
create index on vehicles (plate);

-- ---------- shifts & sales ----------
create table shifts (
  id                 uuid primary key default gen_random_uuid(),   -- may be generated on the device
  station_id         uuid not null references stations(id),
  pump_id            uuid not null,
  attendant_id       uuid not null references auth.users(id),
  opened_at          timestamptz not null default now(),
  closed_at          timestamptz,
  opening_cash       numeric(16,2) not null default 0 check (opening_cash >= 0),
  counted_cash       numeric(16,2) check (counted_cash >= 0),
  status             shift_status not null default 'open',
  diff_reason        text,
  decided_by         uuid references auth.users(id),
  decided_at         timestamptz,
  decision_note      text,
  device_id          text references devices(id),
  client_created_at  timestamptz,
  created_at         timestamptz not null default now(),
  foreign key (station_id, pump_id) references pumps(station_id, id),
  unique (station_id, id)
);
-- Spec: two shifts cannot be open on the same pump at the same time.
create unique index one_open_shift_per_pump on shifts (pump_id) where status in ('open', 'reopened');

create table shift_readings (
  shift_id            uuid not null references shifts(id) on delete cascade,
  nozzle_id           uuid not null references nozzles(id),
  opening_reading     numeric(14,1) not null check (opening_reading >= 0),
  closing_reading     numeric(14,1),
  opening_photo_path  text,
  closing_photo_path  text,
  primary key (shift_id, nozzle_id),
  check (closing_reading is null or closing_reading >= opening_reading)
);

-- Individually recorded fills. NOT every fill is recorded (spec: QR/customer link is optional);
-- cash sales are derived from meter readings at shift close. Card/credit/voucher fills MUST be recorded.
create table sales (
  id                  uuid primary key,              -- generated on the device (idempotent sync)
  station_id          uuid not null references stations(id),
  shift_id            uuid not null,
  nozzle_id           uuid not null,
  liters              numeric(14,3) not null check (liters > 0),
  unit_price          numeric(12,2) not null check (unit_price > 0),
  amount              numeric(16,2) not null check (amount > 0),
  payment_method      payment_method not null,
  customer_id         uuid references customers(id),
  company_account_id  uuid,
  driver_id           uuid references company_drivers(id),
  vehicle_id          uuid references vehicles(id),
  odometer_km         int check (odometer_km >= 0),
  status              sale_status not null default 'recorded',
  void_reason         text,
  created_by          uuid not null references auth.users(id),
  device_id           text references devices(id),
  client_created_at   timestamptz not null,
  received_at         timestamptz not null default now(),
  foreign key (station_id, shift_id) references shifts(station_id, id),
  foreign key (station_id, nozzle_id) references nozzles(station_id, id),
  foreign key (station_id, company_account_id) references company_accounts(station_id, id),
  check (payment_method <> 'credit' or company_account_id is not null),
  check (status <> 'voided' or void_reason is not null)
);
create index on sales (shift_id);
create index on sales (customer_id) where customer_id is not null;
create index on sales (company_account_id) where company_account_id is not null;

create table invoices (
  id           uuid primary key default gen_random_uuid(),
  station_id   uuid not null references stations(id),
  sale_id      uuid not null unique references sales(id),
  number       bigint not null,
  customer_id  uuid references customers(id),
  status       invoice_status not null default 'pending',
  issued_at    timestamptz not null default now(),
  pdf_path     text,
  unique (station_id, number)
);

create table invoice_corrections (
  id            uuid primary key default gen_random_uuid(),
  invoice_id    uuid not null references invoices(id),
  reason        text not null check (length(trim(reason)) > 0),
  amount_delta  numeric(16,2) not null,
  created_by    uuid not null references auth.users(id),
  created_at    timestamptz not null default now()
);

create table company_payments (
  id                  uuid primary key default gen_random_uuid(),
  company_account_id  uuid not null references company_accounts(id),
  amount              numeric(16,2) not null check (amount > 0),
  paid_to             cash_source not null default 'cash',
  received_at         timestamptz not null default now(),
  note                text,
  created_by          uuid not null references auth.users(id)
);

-- ---------- inventory ----------
create table suppliers (
  id          uuid primary key default gen_random_uuid(),
  station_id  uuid not null references stations(id) on delete cascade,
  name        text not null,
  phone       text,
  is_active   boolean not null default true,
  unique (station_id, id)
);

create table fuel_deliveries (
  id                   uuid primary key default gen_random_uuid(),
  station_id           uuid not null references stations(id),
  supplier_id          uuid,
  tank_id              uuid not null,
  liters               numeric(14,3) not null check (liters > 0),
  unit_cost            numeric(12,2) check (unit_cost > 0),   -- NULL = cost not entered yet (profit becomes "estimated")
  extra_costs          numeric(16,2) not null default 0 check (extra_costs >= 0),
  supplier_invoice_no  text,
  attachment_path      text,
  received_at          timestamptz not null default now(),
  created_by           uuid not null references auth.users(id),
  foreign key (station_id, supplier_id) references suppliers(station_id, id),
  foreign key (station_id, tank_id) references tanks(station_id, id)
);

create table tank_measurements (
  id             uuid primary key default gen_random_uuid(),
  station_id     uuid not null references stations(id),
  tank_id        uuid not null,
  measured_l     numeric(14,3) not null check (measured_l >= 0),
  book_l         numeric(14,3) not null,           -- book stock at measurement time (snapshot)
  measured_at    timestamptz not null default now(),
  measured_by    uuid not null references auth.users(id),
  photo_path     text,
  foreign key (station_id, tank_id) references tanks(station_id, id)
);

-- Book stock of a tank = SUM(liters) of its movements. Append-only (see guards migration).
create table inventory_movements (
  id          bigint generated always as identity primary key,
  station_id  uuid not null references stations(id),
  tank_id     uuid not null,
  type        movement_type not null,
  liters      numeric(14,3) not null check (liters <> 0),   -- signed: + into tank, - out of tank
  ref_table   text,
  ref_id      uuid,
  reason      text,
  created_by  uuid references auth.users(id),
  created_at  timestamptz not null default now(),
  foreign key (station_id, tank_id) references tanks(station_id, id),
  check (type not in ('adjustment', 'waste') or reason is not null),
  check ((type in ('receipt', 'return', 'transfer_in') and liters > 0)
      or (type in ('sale', 'waste', 'transfer_out') and liters < 0)
      or  type = 'adjustment')
);
create index on inventory_movements (tank_id, created_at);

-- ---------- expenses ----------
create table expenses (
  id               uuid primary key default gen_random_uuid(),
  station_id       uuid not null references stations(id),
  category         expense_category not null,
  amount           numeric(16,2) not null check (amount > 0),
  paid_from        cash_source not null default 'cash',
  supplier_id      uuid,
  description      text not null,
  expense_date     date not null default current_date,
  attachment_path  text,
  status           entry_status not null default 'draft',
  created_by       uuid not null references auth.users(id),
  created_at       timestamptz not null default now(),
  foreign key (station_id, supplier_id) references suppliers(station_id, id)
);

-- ---------- accounting (double entry) ----------
create table accounts (
  id          uuid primary key default gen_random_uuid(),
  station_id  uuid not null references stations(id) on delete cascade,
  code        text not null,
  name        text not null,
  type        account_type not null,
  is_system   boolean not null default false,      -- used by automatic postings; cannot be deactivated
  is_active   boolean not null default true,
  unique (station_id, code),
  unique (station_id, id)
);

create table accounting_periods (
  id          uuid primary key default gen_random_uuid(),
  station_id  uuid not null references stations(id) on delete cascade,
  starts_on   date not null,
  ends_on     date not null,
  status      period_status not null default 'open',
  closed_by   uuid references auth.users(id),
  closed_at   timestamptz,
  check (ends_on >= starts_on),
  unique (station_id, starts_on)
);

create table journal_entries (
  id                 uuid primary key default gen_random_uuid(),
  station_id         uuid not null references stations(id),
  number             bigint,                        -- assigned on posting
  entry_date         date not null default current_date,
  description        text not null,
  source_table       text,                          -- e.g. 'shifts', 'fuel_deliveries', 'expenses' (NULL = manual)
  source_id          uuid,
  status             entry_status not null default 'draft',
  reverses_entry_id  uuid references journal_entries(id),
  reason             text,
  created_by         uuid references auth.users(id),
  created_at         timestamptz not null default now(),
  posted_at          timestamptz,
  unique (station_id, number),
  unique (station_id, id),
  check (reverses_entry_id is null or reason is not null)
);
create index on journal_entries (station_id, entry_date);
create index on journal_entries (source_table, source_id);
-- one reversal per entry
create unique index one_reversal_per_entry on journal_entries (reverses_entry_id) where reverses_entry_id is not null;

create table journal_lines (
  id          bigint generated always as identity primary key,
  station_id  uuid not null,
  entry_id    uuid not null,
  account_id  uuid not null,
  debit       numeric(16,2) not null default 0 check (debit >= 0),
  credit      numeric(16,2) not null default 0 check (credit >= 0),
  memo        text,
  foreign key (station_id, entry_id) references journal_entries(station_id, id),
  foreign key (station_id, account_id) references accounts(station_id, id),
  check ((debit = 0) <> (credit = 0))              -- exactly one side is positive
);
create index on journal_lines (entry_id);
create index on journal_lines (account_id);

-- ---------- approvals ----------
create table approval_requests (
  id              uuid primary key default gen_random_uuid(),
  station_id      uuid not null references stations(id),
  type            approval_type not null,
  ref_table       text not null,
  ref_id          uuid not null,
  payload         jsonb not null default '{}'::jsonb,   -- snapshot shown to the approver
  requested_by    uuid not null references auth.users(id),
  requested_at    timestamptz not null default now(),
  status          approval_status not null default 'pending',
  decided_by      uuid references auth.users(id),
  decided_at      timestamptz,
  decision_option text,
  decision_note   text
);
create index on approval_requests (station_id, status);
create unique index one_pending_request_per_ref on approval_requests (type, ref_id) where status = 'pending';

-- ---------- customers: loyalty & complaints ----------
create table loyalty_ledger (
  id           bigint generated always as identity primary key,
  customer_id  uuid not null references customers(id),
  station_id   uuid not null references stations(id),
  invoice_id   uuid references invoices(id),
  points       int not null check (points <> 0),
  reason       text not null,
  created_at   timestamptz not null default now()
);

create table offers (
  id           uuid primary key default gen_random_uuid(),
  station_id   uuid not null references stations(id) on delete cascade,
  title        text not null,
  rule         jsonb not null default '{}'::jsonb,
  starts_at    timestamptz not null,
  ends_at      timestamptz not null,
  is_active    boolean not null default true,
  check (ends_at > starts_at)
);

create table complaints (
  id           uuid primary key default gen_random_uuid(),
  station_id   uuid not null references stations(id),
  customer_id  uuid references customers(id),
  invoice_id   uuid references invoices(id),
  kind         complaint_kind not null default 'complaint',
  subject      text not null,
  status       complaint_status not null default 'open',
  sla_due_at   timestamptz not null default now() + interval '48 hours',  -- escalate to platform after
  created_at   timestamptz not null default now(),
  resolved_at  timestamptz
);
create index on complaints (station_id, status);

create table complaint_messages (
  id            bigint generated always as identity primary key,
  complaint_id  uuid not null references complaints(id) on delete cascade,
  author_id     uuid not null references auth.users(id),
  author_side   text not null check (author_side in ('customer', 'station', 'platform')),
  body          text not null,
  created_at    timestamptz not null default now()
);

-- ---------- platform (SaaS) ----------
create table plans (
  id              uuid primary key default gen_random_uuid(),
  code            text not null unique,              -- 'basic', 'pro', 'network'
  name            text not null,
  monthly_price   numeric(16,2) not null check (monthly_price >= 0),
  per_station     boolean not null default false,
  limits          jsonb not null default '{}'::jsonb, -- {"stations":1,"users":5}
  features        text[] not null default '{}'        -- {'credit_accounts','advanced_reports'}
);

create table subscriptions (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references organizations(id),
  plan_id          uuid not null references plans(id),
  status           subscription_status not null default 'trial',
  trial_ends_at    timestamptz,
  renews_at        date,
  created_at       timestamptz not null default now()
);

create table support_tickets (
  id           uuid primary key default gen_random_uuid(),
  number       bigint generated always as identity unique,
  station_id   uuid references stations(id),
  subject      text not null,
  priority     ticket_priority not null default 'medium',
  status       ticket_status not null default 'open',
  assignee_id  uuid references auth.users(id),
  opened_by    uuid references auth.users(id),
  sla_due_at   timestamptz,
  created_at   timestamptz not null default now()
);

create table feature_flags (
  key          text primary key,
  description  text,
  is_unstable  boolean not null default false,
  station_ids  uuid[] not null default '{}'
);

-- Platform staff get NO financial access by default; a time-boxed grant with a written reason is required.
create table access_grants (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id),
  station_id  uuid not null references stations(id),
  reason      text not null check (length(trim(reason)) > 0),
  ticket_id   uuid references support_tickets(id),
  expires_at  timestamptz not null,
  created_at  timestamptz not null default now()
);

-- ---------- audit log (append-only, see guards) ----------
create table audit_log (
  id          bigint generated always as identity primary key,
  at          timestamptz not null default now(),
  actor_id    uuid,
  station_id  uuid,
  action      text not null,                         -- 'insert' | 'update' | 'delete' | domain verbs
  entity      text not null,
  entity_id   text,
  before      jsonb,
  after       jsonb,
  reason      text
);
create index on audit_log (station_id, at desc);

-- ---------- read models ----------
create view tank_book_levels with (security_invoker = true) as
select t.station_id, t.id as tank_id, t.product_id, t.capacity_l,
       coalesce(sum(m.liters), 0)::numeric(14,3) as book_l,
       round(100 * coalesce(sum(m.liters), 0) / t.capacity_l, 1) as book_pct
from tanks t
left join inventory_movements m on m.tank_id = t.id
group by t.id;

create view current_prices with (security_invoker = true) as
select distinct on (station_id, product_id) station_id, product_id, price, effective_at
from prices
where effective_at <= now()
order by station_id, product_id, effective_at desc;

-- Public data for the customer app (also for guests): station, price, availability, update time + source.
-- Owner-rights view on purpose: exposes only public columns.
create view public_station_prices as
select s.id as station_id, s.name as station_name, s.city, s.currency_code,
       p.id as product_id, p.name as product_name,
       cp.price, cp.effective_at as price_updated_at,
       pa.status as availability, pa.source as availability_source, pa.updated_at as availability_updated_at
from stations s
join products p on p.station_id = s.id and p.is_active
left join lateral (
  select price, effective_at from prices pr
  where pr.station_id = s.id and pr.product_id = p.id and pr.effective_at <= now()
  order by pr.effective_at desc limit 1
) cp on true
left join product_availability pa on pa.station_id = s.id and pa.product_id = p.id
where s.status = 'active';
